#!/bin/sh

#noddi_censorByVolumeNumber
sptMsg="`basename $0`:"

nArgsRequired=2

if [ $# -lt $nArgsRequired ]; then
 echo $sptMsg ERROR: need at least $nArgsRequired arguments to run `basename $0`
fi

echo $sptMsg called

dwiInFn=$1
censorInFn=$2
bvalsFn=$3
bvecsFn=$4

tmp=`basename $dwiInFn`
dwiPrefix=`echo $tmp | sed 's/.gz//' | sed 's/.nii//'`
dwiPrefixCensored=$dwiPrefix"_censored"

bvecsFnCensored=$dwiPrefixCensored.bvecs
bvalsFnCensored=$dwiPrefixCensored.bvals

tmpVolPrefix="tmp$$_"

nVols=`fslnvols $dwiInFn`
echo $sptMsg splitting file into $nVols volumes

fslsplit $dwiInFn $tmpVolPrefix -t

grep . $censorInFn | grep -v ^# > volsToRemove.$$

$sptMsg creating censored bvals and bvecs files

cat -n $bvalsFn | awk '{print $1-1, $2}' > $bvalsFnCensored
cat -n $bvecsFn | awk '{print $1-1, $2, $3, $4}' > $bvecsFnCensored

while read line; do
echo $sptMsg removing volume $line
padNum=`printf "%04d" $line`
rm -f "$tmpVolPrefix"$padNum".nii.gz"
echo $sptMsg removing grad dir $line from gradient tables 
grep -v "^$line " $bvecsFnCensored > temp.$$; mv temp.$$ $bvecsFnCensored 
grep -v "^$line " $bvalsFnCensored > temp.$$; mv temp.$$ $bvalsFnCensored 
done < volsToRemove.$$

fslmerge -t $dwiPrefixCensored `ls $tmpVolPrefix* | sort -n` 

rm -f tmp$$*
rm -f volsToRemove.$$

#$censorInFn
