#!/bin/sh

# getBvalsBruker
#Usage
# getBvalsBruker 175
# where 175 is the path under which the method file resides
#
#Input:
# Path which contains a file called 'method' in the Bruker format
#
#Output:
# A list of effective Bvals, one for each volume.
#
#Robert Bussell, UCSD, CFMRI, October 2016

scanDir=$1

sptMsg="$0":

#echo $sptMsg has scanDir=$scanDir

methodFile=$scanDir/method

#echo method file is $methodFile

#startString="PVM_DwDir="
startString="PVM_DwEffBval="
endString="vis"

# Write a Bruker effective Bvalues list from a copy/pasted DwDir param field 

#Get bvals from method file

grep $startString $methodFile -m1 -A1000 \
| grep -v $startString \
| grep $endString -m1 -B1000 \
| grep -v $endString \
| tr '\n' ' ' \
| tr ' ' '\n' \
| sed '/^$/d'
