#!/bin/sh

#create brain only and brain binary mask from DTI data

sptMsg=`basename $0`:
dwiNiiInFile=$1
numB0=$2
threshPercent=$3 #optional
nArgRequired=2

threshPercent=0.2

if [ "$#" -ge "3" ]; then
threshPercent=$3
fi

minClusterSize=1500

FSLOUTPUTTYPE=NIFTI_GZ

echo $sptMsg dwiNiiInFile is $dwiNiiInFile

fslroi $dwiNiiInFile b0_only.nii.gz 0 $numB0

fslmaths b0_only.nii.gz -thrp $threshPercent brain_mask.nii.gz

fslmaths brain_mask.nii.gz -Tmean brain_mask_mean.nii.gz
mv brain_mask_mean.nii.gz brain_mask.nii.gz

fslmaths brain_mask.nii.gz -bin brain_roi.nii.gz

#get rid of islands
rm -f large_cluster_mask.nii.gz
3dclust -prefix large_cluster_mask.nii.gz -dxyz=1 1.01 1500 brain_roi.nii.gz
mv large_cluster_mask.nii.gz brain_roi.nii.gz

fslmaths brain_roi.nii.gz -mul $dwiNiiInFile dwi_brain_only.nii.gz

echo $sptMsg exiting
