#!/bin/sh

launchDir=`pwd`

#set up fsl environment

source setupFslEnv

#file locations
subjDir=Subject01
studyDir=Study01
noddiDir=$studyDir/$subjDir

noddi_preprocImmunoTypeInputData

cd $launchDir/$noddiDir; noddi_checkInputFiles; cd $launchDir

noddi_runAmicoNoddi $studyDir $subjDir
