#!/bin/sh
#Create a multi-shell bvecs file and bvals file using a single shell as output by getBValsBruker Nov 18 2015 09:21 version
# Example: noddi_makeMultiShellBvalsBvecs bvecs_single bvals_single 5 3 750 1500 2000

numB0=$3
numShells=$4
shell1B=$5
shell2B=$6
if [ $numShells -eq "3" ];then
shell3B=$7
fi

shellSize=30

singleShellBvecsFile=$1
multiShellBvecsOutFile="bvecs_multi.txt"

singleShellBvalsFile=$2
multiShellBvalsOutFile="bvals_multi.txt"

b0DirVec="0.0 0.0 0.0"
b0Val=0.0


rm -f $multiShellBvecsOutFile 
rm -f $multiShellBvalsOutFile 

#add the b0 directions
cnt=0
while [[ "$cnt" -lt "$numB0" ]];do
echo $b0DirVec >> $multiShellBvecsOutFile
cnt=$(($cnt+1))
done

#add the shell-interleaved b vectors
while read line; do
cnt=0
while [[ "$cnt" -lt "$numShells" ]];do
echo $line >> $multiShellBvecsOutFile
#echo $line
#echo $singleShellBvecsFile
cnt=$(($cnt+1))
done
done < $singleShellBvecsFile


#****make the bvals files****

#B0 bvals
cnt=0
while [[ "$cnt" -lt "$numB0" ]];do
echo $b0Val >> $multiShellBvalsOutFile
cnt=$(($cnt+1))
done


#add the shell-interleaved b vectors
cnt=0
while [[ "$cnt" -lt "$shellSize" ]];do
echo $shell1B >> $multiShellBvalsOutFile
echo $shell2B >> $multiShellBvalsOutFile
if [ "$numShells" -eq "3"  ] ;then
echo $shell3B >> $multiShellBvalsOutFile
fi
cnt=$(($cnt+1))
done

#cleanup
rm bvec.$$
