#!/bin/sh

#create brain only and brain binary mask from DTI data

dwiNiiInFile=$1
numB0=$2
nArgRequired=2

threshPercent=40

if [ "$#" -ge "3" ]; then
threshPercent=$3
fi

FSLOUTPUTTYPE=NIFTI_GZ

echo $dwiNiiInFile

fslroi $dwiNiiInFile b0_only.nii.gz 0 $numB0

fslmaths b0_only.nii.gz -thrp $threshPercent brain_mask.nii.gz

fslmaths brain_mask.nii.gz -Tmean brain_mask_mean.nii.gz
mv brain_mask_mean.nii.gz brain_mask.nii.gz

fslmaths brain_mask.nii.gz -bin brain_roi.nii.gz

fslmaths brain_roi.nii.gz -mul $dwiNiiInFile dwi_brain_only.nii.gz
