#!/bin/bash


#Sort out host and container file location
hostCurDir=`pwd`
contUserName=`id -un`
#contUserName=cfmriguest
contHome=/home/$contUserName
contDataDir=$contHome/data/

containerName=$1

case $containerName in
	noddi1|noddi2|noddi3|noddi4|noddi5|noddi6|noddi7|noddi8) echo found valid container name $containerName;;
	*) echo did not find a valid container name, exiting; exit;;
esac

#docker run -i --name $containerName \
docker run --name $containerName \
--rm -v $hostCurDir/:$contDataDir \
-e LOCAL_USER_ID=`id -u $USER` \
-e LOCAL_USER_NAME=`id -un $USER` \
noddi:latest

#docker run -it --name noddi1002 --rm -v /rpool/home/rbussell/data/180209_ruth_noddi/1002/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0

#docker run -it --name container1 --rm -v /home/rbussell/data/noddidata/:/home/cfmriguest/data noddi
