#!/bin/bash

cnt=1
while [[ $cnt -le 1 ]] ; do
#echo $cnt
noddiCmd="./noddiAmicoScript kent Subject$cnt"
echo "******" running noddi amico analysis: $noddiCmd "******" 
$noddiCmd
cnt=$(( cnt + 1 ))
done
