#!/bin/sh

$NODDI_PATH/noddi_fixBFiles bvals
$NODDI_PATH/noddi_fixBFiles bvals

subNumPrefix=T1
rawDir=/rpool/home/rbussell/data/noddi/jacobus/T1
pushd $rawDir
subNums=`ls "$subNumPrefix"???-???? -d | sort -n | uniq`
popd

echo ----
echo found these subnums
echo $subNums
echo ----

dtiFn=dti_topup_eddy.nii.gz
maskFn=mask_mask.nii.gz
bvalsFn=bvals.1D
bvecsFn=bvecs.1D
studyDir=Study01
subjectDir=Subject01


# copy the noddi input files into a common subdirectory
# with conventional filenames
for subNum in $subNums
do
 curSubDir=$rawDir/$subNum
 noddiDir=$curSubDir/noddi

 if [ ! -d "$curSubDir" ]; then
   echo ERROR! $curSubDir does not exist. EXITING!
 fi
 cd $rawDir/$subNum
 if [ ! -d "$noddiDir" ]; then
   mkdir -p $noddiDir
 fi
 cp $maskFn "$noddiDir"/mask_mask.nii.gz
 cp DTI_topup_*_eddy.nii.gz $noddiDir/$dtiFn
 cp bvecs.1D $noddiDir/bvecs.1D
 cp bvals.1D $noddiDir/bvals.1D
done

preProcCmd=/rpool/home/rbussell/repos/noddi/noddi_setupData
noddiCmd=/rpool/home/rbussell/repos/noddi/noddi_runContainer


for subNum in $subNums
do
  echo preprocessing sub $subNum for noddi analysis
  curSubDir=$rawDir/$subNum
  noddiDir=$curSubDir/noddi
  cd $noddiDir
  echo calling preproc command in dir $PWD
  $preProcCmd dti_topup_eddy.nii.gz Study01 Study01/Subject01 bvals.1D bvecs.1D mask_mask.nii.gz mask_mask.nii.gz
  $noddiCmd
  cd $rawDir
done

docker run -it --name noddi1 --rm -v /rpool/home/rbussell/data/noddi/jacobus/T1/T1001-0116/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
docker run -it --name noddi1 --rm -v /rpool/home/rbussell/data/noddi/jacobus/T1/T1001-0116/noddi:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main


#docker run -it --name noddi1 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_198/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi2 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_201/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi3 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_204/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi4 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_205/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi5 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_207/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi6 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_209/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi7 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_214/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
##ABOVE THIS LINE ALREADY RUNNING ON FMRI1----------
#docker run -it --name noddi8 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_222/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi9 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_227/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main
#docker run -it --name noddi10 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_235/dti/:/home/rbussell/data/ -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_USER_NAME=`id -un $USER` noddi:v1.0 noddi_main

#docker run -it --name noddi198 --rm -v /rpool/home/rbussell/data/noddi/ScottSorgLisaDW/NODDI_pilot_data/TBI_198/dti/:/home/cfmriguest/data/ noddi:v1.0
